### ISSUE TITLE
get pulseaudio default device progamatically

### ISSUE THREAD

**Issue by faebser** [faebser/azure-ai-code#5]
because pulseaudio is a bitch we need to find the default device in code.

**Comment by lukemodular** [comment]
From https://github.com/alphacep/vosk-api/blob/master/python/example/test_microphone.py:
help='input device (numeric ID or substring)
Seems to be as as easy as this: just use "default" or "pulse" as ID value.

**Comment by faebser** [comment]
was fixed in https://github.com/faebser/azure-ai-code/commit/5574d7d97983c3b549149d1bc5488a88b6712876
